### ISSUE TITLE
Compilation error: /usr/bin/ld: cannot find -lFIST.linux64

### ISSUE THREAD

**Issue by sayhitosandy** [jmlien/acd2d#1]
I tried compiling your code, but got the following error on running make command:
![image 1](https://user-images.githubusercontent.com/19322983/37400159-0508d6a6-27aa-11e8-8f93-0cbcecc95d3b.png)

There's an issue with FIST library, as it could not find lFIST.linux64. My system is Ubuntu 16.04LTS 64-bit. Kindly check.

**Comment by jmlien** [comment]
Files has been added.
